=== anirbanmu/dagbot/commands/schema/calendarcountdown.json
{
    "$schema": "http://json-schema.org/schema#",
    "title": "Calendar countdown config",
    "type": "array",
    "default": [],
    "items": {
        "type": "object",
        "properties": {
            "identifiers": {
                "description": "Identifiers to identify this countdown",
                "type": "array",
                "minItems": 1,
                "items": {
                    "type": "string"
                }
            },
            "descriptor": {
                "description": "A string to describe the events in this calendar",
                "type": "string"
            },
            "calendar_url": {
                "type": "string"
            },
            "filters": {
                "description": "Mapping of filter shortcuts to a searchable string to use in filtering calendar events",
                "type": "object",
                "default": {},
                "additionalProperties": {
                    "type": "object",
                    "properties": {
                        "event_field_name": {
                            "type": "string",
                            "default": "name"
                        },
                        "filter_string": {
                            "type": "string"
                        }
                    },
                    "required": ["filter_string"]
                }
            },
            "default_id": {
                "description": "If no identifier is found, use this one",
                "type": "boolean"
            },
            "required_string": {
                "description": "Ignore any events that do not have this string in their descriptions",
                "type": "string",
                "default": ""
            }
        },
        "required": ["identifiers", "descriptor", "calendar_url"]
    }
}

=== anirbanmu/dagbot/commands/config/calendarcountdown.json
[
    {
        "identifiers": ["f1", "formula1"],
        "descriptor": "Formula 1",
        "calendar_url": "https://www.f1calendar.com/download/f1-calendar_p1_p2_p3_q_gp.ics",
        "filters": {
            "r": { "filter_string": "grand prix", "event_field_name": "categories" },
            "q": { "filter_string": "qualifying", "event_field_name": "categories" },
            "fp1": { "filter_string": "first practice", "event_field_name": "categories"  },
            "fp2": { "filter_string": "second practice", "event_field_name": "categories" },
            "fp3": { "filter_string": "third practice", "event_field_name": "categories" }
        },
        "default_id": true
    },
    {
        "identifiers": ["wec"],
        "descriptor": "FIA World Endurance Championship",
        "calendar_url": "http://rmotorsportscalendar.com/calendar/x306b9722e.ics",
        "filters": {
            "r": { "filter_string": "race" },
            "q": { "filter_string": "qualifying" }
        }
    },
    {
        "identifiers": ["gp2", "f2", "formula2"],
        "descriptor": "GP2 Series",
        "calendar_url": "http://www.rmotorsportscalendar.com/calendar/w8a3e9a013.ics",
        "filters": {
            "r": { "filter_string": "race" },
            "q": { "filter_string": "qualifying" }
        }
    },
    {
        "identifiers": ["gp3"],
        "descriptor": "GP3 Series",
        "calendar_url": "http://www.rmotorsportscalendar.com/calendar/ye16d39716.ics",
        "filters": {
            "r": { "filter_string": "race" },
            "q": { "filter_string": "qualifying" }
        }
    },
    {
        "identifiers": ["fe", "formulae", "formula-e"],
        "descriptor": "FIA Formula-E",
        "calendar_url": "http://calendar.google.com/calendar/ical/vnfvu78fj9365bs5oiuga7sa90%40group.calendar.google.com/public/basic.ics",
        "filters": {
            "r": { "filter_string": "race" },
            "q": { "filter_string": "quali" },
            "p": { "filter_string": "practice" }
        }
    },
    {
        "identifiers": ["irl", "indy", "indycar"],
        "descriptor": "Verizon Indycar Series",
        "calendar_url": "http://rmotorsportscalendar.com/calendar/b815a32e31.ics",
        "filters": {
            "r": { "filter_string": "race" },
            "q": { "filter_string": "qualifying" },
            "p1": { "filter_string": "practice 1" },
            "p2": { "filter_string": "practice 2" },
            "p3": { "filter_string": "practice 3" }
        }
    },
    {
        "identifiers": ["dtm"],
        "descriptor": "Deutsche Tourenwagen Masters",
        "calendar_url": "http://rmotorsportscalendar.com/calendar/t116951d81.ics",
        "filters": {}
    },
    {
        "identifiers": ["v8sc", "v8supercars", "v8straya", "v8"],
        "descriptor": "V8 Supercars",
        "calendar_url": "http://rmotorsportscalendar.com/calendar/e0995e2100.ics",
        "filters": {
            "r": { "filter_string": "race" },
            "r1": { "filter_string": "race 1" },
            "r2": { "filter_string": "race 2" },
            "r3": { "filter_string": "race 3" },
            "q1": { "filter_string": "qualifying 1" },
            "q2": { "filter_string": "qualifying 2" },
            "q3": { "filter_string": "qualifying 3" },
            "p1": { "filter_string": "practice 1" },
            "p2": { "filter_string": "practice 2" },
            "p3": { "filter_string": "practice 3" },
            "s": { "filter_string": "shootout" }
        }
    },
    {
        "identifiers": ["uscr", "imsa"],
        "descriptor": "WeatherTech SportsCar Championship",
        "calendar_url": "http://rmotorsportscalendar.com/calendar/l15142020e.ics",
        "filters": {
            "r": { "filter_string": "race" },
            "q": { "filter_string": "qualifying" },
            "p1": { "filter_string": "practice 1" },
            "p2": { "filter_string": "practice 2" },
            "p3": { "filter_string": "practice 3" },
            "p4": { "filter_string": "practice 4" }
        }
    },
    {
        "identifiers": ["motogp", "moto"],
        "descriptor": "MotoGP",
        "calendar_url": "https://www.google.com/calendar/ical/832vbii8pmrvma356b4vn3v42c@group.calendar.google.com/public/basic.ics",
        "filters": {
            "r": { "filter_string": "race" },
            "q": { "filter_string": "qualifying" },
            "q1": { "filter_string": "qualifying 1" },
            "q2": { "filter_string": "qualifying 2" },
            "fp1": { "filter_string": "practice 1" },
            "fp2": { "filter_string": "practice 2" },
            "fp3": { "filter_string": "practice 3" },
            "fp4": { "filter_string": "practice 4" }
        }
    },
    {
        "identifiers": ["wsbk", "sbk", "worldsbk"],
        "descriptor": "WorldSBK",
        "calendar_url": "http://rmotorsportscalendar.com/calendar/y85d7d2182.ics",
        "filters": {
            "r": { "filter_string": "race" },
            "q": { "filter_string": "qualifying" },
            "q1": { "filter_string": "qualifying 1" },
            "q2": { "filter_string": "qualifying 2" },
            "p": { "filter_string": "practice" },
            "p1": { "filter_string": "practice 1" },
            "p2": { "filter_string": "practice 2" },
            "p3": { "filter_string": "practice 3" },
            "p4": { "filter_string": "practice 4" }
        }
    },
    {
        "identifiers": ["moto2"],
        "descriptor": "Moto2",
        "calendar_url": "http://www.rmotorsportscalendar.com/calendar/pd73de8639.ics",
        "filters": {
            "r": { "filter_string": "race" },
            "q": { "filter_string": "qualifying" },
            "fp1": { "filter_string": "practice 1" },
            "fp2": { "filter_string": "practice 2" },
            "fp3": { "filter_string": "practice 3" }
        }
    },
    {
        "identifiers": ["moto3"],
        "descriptor": "Moto3",
        "calendar_url": "http://www.rmotorsportscalendar.com/calendar/a7b113dee2.ics",
        "filters": {
            "r": { "filter_string": "race" },
            "q": { "filter_string": "qualifying" },
            "fp1": { "filter_string": "practice 1" },
            "fp2": { "filter_string": "practice 2" },
            "fp3": { "filter_string": "practice 3" }
        }
    },
    {
        "identifiers": ["wrc", "rally"],
        "descriptor": "World Rally Championship",
        "calendar_url": "http://rmotorsportscalendar.com/calendar/c3f63e0d4c.ics",
        "filters": {}
    },
    {
        "identifiers": ["wrx", "rallycross"],
        "descriptor": "World Rallycross Championship",
        "calendar_url": "http://rmotorsportscalendar.com/calendar/y64c4a1b7e.ics",
        "filters": {}
    },
    {
        "identifiers": ["nascar", "MENCS"],
        "descriptor": "Monster Energy NASCAR Cup Series",
        "calendar_url": "http://rmotorsportscalendar.com/calendar/gcd09c08ae.ics",
        "filters": {
            "r": { "filter_string": "race" },
            "q": { "filter_string": "qualifying" },
            "p1": { "filter_string": "practice 1" },
            "p2": { "filter_string": "practice 2" },
            "p3": { "filter_string": "practice 3" }
        }
    },
    {
        "identifiers": ["blancpain", "blanc"],
        "descriptor": "Blancpain GT Series",
        "calendar_url": "http://rmotorsportscalendar.com/calendar/accf915a1f.ics",
        "filters": {
            "r": { "filter_string": "race" },
            "q": { "filter_string": "qualifying" },
            "qr": { "filter_string": "qualifying race" },
            "mr": { "filter_string": "main race" },
            "fp1": { "filter_string": "practice 1" },
            "fp2": { "filter_string": "practice 2" }
        }
    },
    {
        "identifiers": ["formulad", "fd"],
        "descriptor": "Formula Drift",
        "calendar_url": "http://rmotorsportscalendar.com/calendar/t019b6c053.ics",
        "filters": {}
    },
    {
        "identifiers": ["supergt", "sgt"],
        "descriptor": "Super GT",
        "calendar_url": "http://rmotorsportscalendar.com/calendar/cb81f3a27f.ics",
        "filters": {
            "r": { "filter_string": "race" },
            "q": { "filter_string": "qualifying" },
            "p": { "filter_string": "practice" }
        }
    },
    {
        "identifiers": ["wtcr", "touring"],
        "descriptor": "World Touring Car Cup",
        "calendar_url": "http://rmotorsportscalendar.com/calendar/r2384e438a.ics",
        "filters": {
            "p": { "filter_string": "practice" },
            "p1": { "filter_string": "practice 1" },
            "p2": { "filter_string": "practice 2" },
            "q": { "filter_string": "qualifying" },
            "q1": { "filter_string": "qualifying 1" },
            "q2": { "filter_string": "qualifying 2" },
            "r": { "filter_string": "race" },
            "r1": { "filter_string": "race 1" },
            "r2": { "filter_string": "race 2" },
            "r3": { "filter_string": "race 3" }
        }
    }
]
